import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import HeaderNav from '@/components/Header'
import Providers from '@/providers/react-query-provider'
import { NotificationProvider } from '@/contexts/NotificationContext';
import Notification from '@/components/Notification';
import DarkModeSwitch from '@/components/DarkModeSwitch'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        {/* {process.env.NODE_ENV === 'development' && (
          <Script
            src="https://unpkg.com/react-scan/dist/auto.global.js"
            strategy="beforeInteractive"
          />
        )} */}
        <NotificationProvider>
          <Providers>
            <HeaderNav />
            {children}
            <Notification />
            <DarkModeSwitch />
          </Providers>
        </NotificationProvider>
      </body>
    </html>
  )
}